/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresselRouteImport } from './routes/pressel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGeneratePixRouteImport } from './routes/api/public/generate-pix'

const PresselRoute = PresselRouteImport.update({
  id: '/pressel',
  path: '/pressel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeneratePixRoute = ApiPublicGeneratePixRouteImport.update({
  id: '/api/public/generate-pix',
  path: '/api/public/generate-pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pressel': typeof PresselRoute
  '/api/public/generate-pix': typeof ApiPublicGeneratePixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pressel': typeof PresselRoute
  '/api/public/generate-pix': typeof ApiPublicGeneratePixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pressel': typeof PresselRoute
  '/api/public/generate-pix': typeof ApiPublicGeneratePixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pressel' | '/api/public/generate-pix'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pressel' | '/api/public/generate-pix'
  id: '__root__' | '/' | '/pressel' | '/api/public/generate-pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresselRoute: typeof PresselRoute
  ApiPublicGeneratePixRoute: typeof ApiPublicGeneratePixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pressel': {
      id: '/pressel'
      path: '/pressel'
      fullPath: '/pressel'
      preLoaderRoute: typeof PresselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-pix': {
      id: '/api/public/generate-pix'
      path: '/api/public/generate-pix'
      fullPath: '/api/public/generate-pix'
      preLoaderRoute: typeof ApiPublicGeneratePixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresselRoute: PresselRoute,
  ApiPublicGeneratePixRoute: ApiPublicGeneratePixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
